affiliates_connect_flipkart.settings:
  type: config_object
  label: 'Affiliates Connect Flipkart settings'
  mapping:
    native_api:
      type: boolean
      label: 'Allows usage Affiliate Marketing using tracking ID'
    flipkart_tracking_id:
      type: string
      label: 'Input tracking ID of corresponding Affiliate API'
    flipkart_token:
      type: string
      label: 'Input token of corresponding Affiliate API'
    data_storage:
      type: boolean
      label: 'Allows storing product data in your site database'
    import:
      type: string
      label: 'Import period for Affiliate Native API through Crons'
    full_content:
      type: boolean
      label: 'Allows updating of full content'
    price:
      type: boolean
      label: 'Allows updating of price'
    available:
      type: boolean
      label: 'Allows updating of products availability'
    size:
      type: boolean
      label: 'Allows updating of size'
    color:
      type: boolean
      label: 'Allows updating of color'
    offers:
      type: boolean
      label: 'Allows updating of offers'

